name: chineasy
description: A new Flutter project.
version: 1.0.0+1
<<<<<<< HEAD
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
=======
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
>>>>>>> 745dc441913e5d902d5c69af130cc3f3de232b4a
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  outline_gradient_button: ^2.0.1+1
  flutter_svg_provider: ^1.0.7
<<<<<<< HEAD
  provider: ^6.1.2
  download: ^1.0.0
  flutter_glow: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
=======
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Montserrat
      fonts: 
>>>>>>> 745dc441913e5d902d5c69af130cc3f3de232b4a
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400
    - family: Poppins
<<<<<<< HEAD
      fonts:
=======
      fonts: 
>>>>>>> 745dc441913e5d902d5c69af130cc3f3de232b4a
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Outfit
<<<<<<< HEAD
      fonts:
=======
      fonts: 
>>>>>>> 745dc441913e5d902d5c69af130cc3f3de232b4a
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
        - asset: assets/fonts/OutfitBold.ttf
          weight: 700
    - family: Alata
<<<<<<< HEAD
      fonts:
        - asset: assets/fonts/AlataRegular.ttf
          weight: 400
    - family: Inter
      fonts:
=======
      fonts: 
        - asset: assets/fonts/AlataRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
>>>>>>> 745dc441913e5d902d5c69af130cc3f3de232b4a
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Oxygen
<<<<<<< HEAD
      fonts:
        - asset: assets/fonts/OxygenBold.ttf
          weight: 700
    - family: Paytone One
      fonts:
        - asset: assets/fonts/PaytoneOneRegular.ttf
          weight: 400
    - family: Oooh Baby
      fonts:
=======
      fonts: 
        - asset: assets/fonts/OxygenBold.ttf
          weight: 700
    - family: Paytone One
      fonts: 
        - asset: assets/fonts/PaytoneOneRegular.ttf
          weight: 400
    - family: Oooh Baby
      fonts: 
>>>>>>> 745dc441913e5d902d5c69af130cc3f3de232b4a
        - asset: assets/fonts/OoohBabyRegular.ttf
          weight: 400
