import '../Flashcards_Models/word.dart';

final List<Word> words = [
  Word(
      topic: "Engineering",
      english: "Engineer",
      character: "工程师",
      pinyin: "gōngchéngshī"),
  Word(
      topic: "Engineering",
      english: "Computer",
      character: "电脑",
      pinyin: "diànnǎo"),
  Word(
      topic: "Engineering",
      english: "Software",
      character: "软件",
      pinyin: "ruǎnjiàn"),
  Word(
      topic: "Engineering",
      english: "Hardware",
      character: "硬件",
      pinyin: "yìngjiàn"),
  Word(
      topic: "Engineering",
      english: "Robot",
      character: "机器人",
      pinyin: "jīqìrén"),
  Word(
      topic: "Engineering",
      english: "Internet",
      character: "互联网",
      pinyin: "hùliánwǎng"),
  Word(
      topic: "Engineering",
      english: "Electrical Engineering",
      character: "电气工程",
      pinyin: "diànqìgōngchéng"),
  Word(
      topic: "Engineering",
      english: "Mechanical Engineering",
      character: "机械工程",
      pinyin: "jīxiègōngchéng"),
  Word(
      topic: "Engineering",
      english: "Civil Engineering",
      character: "土木工程",
      pinyin: "tǔmùgōngchéng"),
  Word(
      topic: "Business",
      english: "Business",
      character: "商业",
      pinyin: "shāngyè"),
  Word(
      topic: "Business",
      english: "Businessman",
      character: "商人",
      pinyin: "shāngrén"),
  Word(
      topic: "Business",
      english: "Economics",
      character: "经济学",
      pinyin: "jīngjìxué"),
  Word(
      topic: "Business",
      english: "Accounting",
      character: "会计",
      pinyin: "kuàijì"),
  Word(
      topic: "Business",
      english: "Marketing",
      character: "市场营销",
      pinyin: "shìchǎngyíngxiāo"),
  Word(
      topic: "Business",
      english: "Finance",
      character: "金融",
      pinyin: "jīnróng"),
  Word(topic: "Business", english: "Stock", character: "股票", pinyin: "gǔpiào"),
  Word(
      topic: "Business",
      english: "Investment",
      character: "投资",
      pinyin: "tóuzī"),
  Word(topic: "Business", english: "Bank", character: "银行", pinyin: "yínháng"),
  Word(topic: "Business", english: "Money", character: "钱", pinyin: "qián"),
  Word(topic: "Business", english: "Salary", character: "工资", pinyin: "gōngzī"),
  Word(topic: "Business", english: "Budget", character: "预算", pinyin: "yùsuàn"),
  Word(topic: "Business", english: "Profit", character: "利润", pinyin: "lìrùn"),
  Word(
      topic: "Physical Therapy",
      english: "Physical Therapy",
      character: "物理治疗",
      pinyin: "wùlǐzhìliáo"),
  Word(
      topic: "Physical Therapy",
      english: "Physical Therapist",
      character: "物理治疗师",
      pinyin: "wùlǐzhìliáoshī"),
  Word(
      topic: "Physical Therapy",
      english: "Exercise",
      character: "锻炼",
      pinyin: "duànliàn"),
  Word(
      topic: "Physical Therapy",
      english: "Stretch",
      character: "伸展",
      pinyin: "shēnzhǎn"),
  Word(
      topic: "Physical Therapy",
      english: "Strength",
      character: "力量",
      pinyin: "lìliàng"),
  Word(
      topic: "Physical Therapy",
      english: "Flexibility",
      character: "灵活性",
      pinyin: "línghuóxìng"),
  Word(
      topic: "Physical Therapy",
      english: "Balance",
      character: "平衡",
      pinyin: "pínghéng"),
  Word(
      topic: "Physical Therapy",
      english: "Endurance",
      character: "耐力",
      pinyin: "nàilì"),
  Word(
      topic: "Physical Therapy",
      english: "Pain",
      character: "疼痛",
      pinyin: "téngtòng"),
  Word(
      topic: "Physical Therapy",
      english: "Injury",
      character: "受伤",
      pinyin: "shòushāng"),
  Word(
      topic: "Physical Therapy",
      english: "Rehabilitation",
      character: "康复",
      pinyin: "kāngfù"),
  Word(
      topic: "Pharmacy",
      english: "Pharmacy",
      character: "药房",
      pinyin: "yàofáng"),
  Word(
      topic: "Pharmacy",
      english: "Pharmacist",
      character: "药剂师",
      pinyin: "yàojìshī"),
  Word(
      topic: "Pharmacy",
      english: "Prescription",
      character: "处方",
      pinyin: "chǔfāng"),
  Word(topic: "Pharmacy", english: "Medicine", character: "药", pinyin: "yào"),
  Word(topic: "Pharmacy", english: "Pill", character: "药丸", pinyin: "yàowán"),
  Word(
      topic: "Pharmacy", english: "Tablet", character: "片剂", pinyin: "piàn jì"),
  Word(
      topic: "Pharmacy",
      english: "Capsule",
      character: "胶囊",
      pinyin: "jiāonáng"),
  Word(
      topic: "Pharmacy",
      english: "Syrup",
      character: "糖浆",
      pinyin: "tángjiāng"),
  Word(
      topic: "Pharmacy",
      english: "Ointment",
      character: "药膏",
      pinyin: "yàogāo"),
  Word(
      topic: "Pharmacy",
      english: "Injection",
      character: "注射",
      pinyin: "zhùshè"),
  Word(
      topic: "Pharmacy", english: "Vaccine", character: "疫苗", pinyin: "yìmiáo"),
  Word(
      topic: "Computer Science",
      english: "Computer Science",
      character: "计算机科学",
      pinyin: "jìsuànjīkēxué"),
  Word(
      topic: "Computer Science",
      english: "Programming",
      character: "编程",
      pinyin: "biānchéng"),
  Word(
      topic: "Computer Science",
      english: "Software Development",
      character: "软件开发",
      pinyin: "ruǎnjiànkāifā"),
  Word(
      topic: "Computer Science",
      english: "Web Development",
      character: "网站开发",
      pinyin: "wǎngzhànkāifā"),
  Word(
      topic: "Computer Science",
      english: "Database",
      character: "数据库",
      pinyin: "shùjùkù"),
  Word(
      topic: "Computer Science",
      english: "Network",
      character: "网络",
      pinyin: "wǎngluò"),
  Word(
      topic: "Computer Science",
      english: "Cybersecurity",
      character: "网络安全",
      pinyin: "wǎngluòānquán"),
  Word(
      topic: "Computer Science",
      english: "Artificial Intelligence",
      character: "人工智能",
      pinyin: "réngōngzhìnéng"),
  Word(
      topic: "Computer Science",
      english: "Machine Learning",
      character: "机器学习",
      pinyin: "jīqìxuéxí"),
  Word(
      topic: "Computer Science",
      english: "Data Science",
      character: "数据科学",
      pinyin: "shùjùkēxué"),
  Word(topic: "Beach", english: "Swimsuit", character: "泳衣", pinyin: "yǒngyī"),
  Word(topic: "Beach", english: "Beach", character: "沙滩", pinyin: "shātān"),
  Word(
      topic: "Beach",
      english: "Sunscreen",
      character: "防晒霜",
      pinyin: "fángshàishuāng"),
  Word(
      topic: "Beach",
      english: "Sunglasses",
      character: "太阳镜",
      pinyin: "tàiyángjìng"),
  Word(topic: "China", english: "China", character: "中国", pinyin: "zhōngguó"),
  Word(
      topic: "China",
      english: "Chinese",
      character: "中国人",
      pinyin: "zhōngguórén"),
  Word(topic: "China", english: "Beijing", character: "北京", pinyin: "běijīng"),
  Word(
      topic: "China", english: "Shanghai", character: "上海", pinyin: "shànghǎi"),
  Word(topic: "Food", english: "Food", character: "食物", pinyin: "shíwù"),
  Word(topic: "Food", english: "Rice", character: "米饭", pinyin: "mǐfàn"),
  Word(topic: "Food", english: "Noodles", character: "面条", pinyin: "miàntiáo"),
  Word(topic: "Food", english: "Dumplings", character: "饺子", pinyin: "jiǎozi"),
  Word(topic: "Food", english: "Soup", character: "汤", pinyin: "tāng"),
  Word(topic: "Food", english: "Vegetables", character: "蔬菜", pinyin: "shūcài"),
  Word(topic: "Food", english: "Fruit", character: "水果", pinyin: "shuǐguǒ"),
  Word(topic: "Food", english: "Meat", character: "肉", pinyin: "ròu"),
  Word(
      topic: "Sites",
      english: "Great Wall",
      character: "长城",
      pinyin: "chángchéng"),
  Word(
      topic: "Sites",
      english: "Forbidden City",
      character: "故宫",
      pinyin: "gùgōng"),
  Word(
      topic: "Sites",
      english: "Terracotta Army",
      character: "兵马俑",
      pinyin: "bīngmǎyǒng"),
  Word(
      topic: "Sites",
      english: "Potala Palace",
      character: "布达拉宫",
      pinyin: "bùdálāgōng"),
  Word(
      topic: "Sites",
      english: "Yellow Mountains",
      character: "黄山",
      pinyin: "huángshān"),
  Word(topic: "Drinks", english: "Water", character: "水", pinyin: "shuǐ"),
  Word(topic: "Drinks", english: "Tea", character: "茶", pinyin: "chá"),
  Word(topic: "Drinks", english: "Coffee", character: "咖啡", pinyin: "kāfēi"),
  Word(topic: "Drinks", english: "Milk", character: "牛奶", pinyin: "niúnǎi"),
  Word(topic: "Drinks", english: "Juice", character: "果汁", pinyin: "guǒzhī"),
  Word(
      topic: "Travelling",
      english: "Travel",
      character: "旅行",
      pinyin: "lǚxíng"),
  Word(topic: "Travelling", english: "Plane", character: "飞机", pinyin: "fēijī"),
  Word(
      topic: "Travelling", english: "Train", character: "火车", pinyin: "huǒchē"),
  Word(
      topic: "Travelling",
      english: "Bus",
      character: "公共汽车",
      pinyin: "gōnggòngqìchē"),
  Word(topic: "Travelling", english: "Car", character: "汽车", pinyin: "qìchē"),
  Word(topic: "Customs", english: "Hello", character: "你好", pinyin: "nǐhǎo"),
  Word(
      topic: "Customs", english: "Goodbye", character: "再见", pinyin: "zàijiàn"),
  Word(
      topic: "Customs",
      english: "Thank you",
      character: "谢谢",
      pinyin: "xièxiè"),
  Word(
      topic: "Customs",
      english: "You're welcome",
      character: "不客气",
      pinyin: "bùkèqì"),
  Word(
      topic: "Customs",
      english: "I'm sorry",
      character: "对不起",
      pinyin: "duìbùqǐ"),
  Word(
      topic: "Customs",
      english: "Excuse me",
      character: "对不起",
      pinyin: "duìbùqǐ"),
  Word(topic: "Customs", english: "Yes", character: "是", pinyin: "shì"),
  Word(topic: "Customs", english: "No", character: "不", pinyin: "bù"),
  Word(
      topic: "Customs",
      english: "How much?",
      character: "多少钱",
      pinyin: "duōshǎo qián"),
  Word(
      topic: "Customs",
      english: "Where is the bathroom?",
      character: "洗手间在哪里",
      pinyin: "xǐshǒujiān zài nǎlǐ"),
  Word(
      topic: "Customs",
      english: "I don't understand",
      character: "我不懂",
      pinyin: "wǒ bù dǒng"),
  Word(
      topic: "Customs",
      english: "Do you speak English?",
      character: "你会说英语吗",
      pinyin: "nǐ huì shuō yīngyǔ ma"),
  Word(
      topic: "Customs",
      english: "I don't speak Chinese",
      character: "我不会说中文",
      pinyin: "wǒ bù huì shuō zhōngwén"),
  Word(
      topic: "Traditions",
      english: "Chinese New Year",
      character: "春节",
      pinyin: "chūnjié"),
  Word(
      topic: "Traditions",
      english: "Lantern Festival",
      character: "元宵节",
      pinyin: "yuánxiāojié"),
  Word(
      topic: "Traditions",
      english: "Dragon Boat Festival",
      character: "端午节",
      pinyin: "duānwǔjié"),
  Word(
      topic: "Traditions",
      english: "Mid-Autumn Festival",
      character: "中秋节",
      pinyin: "zhōngqiūjié"),
  Word(
      topic: "Traditions",
      english: "Double Ninth Festival",
      character: "重阳节",
      pinyin: "chóngyángjié"),
  Word(
      topic: "Traditions",
      english: "Spring Festival",
      character: "春节",
      pinyin: "chūnjié"),
  Word(
      topic: "Traditions",
      english: "Qingming Festival",
      character: "清明节",
      pinyin: "qīngmíngjié"),
  Word(topic: "Costumes", english: "Hanfu", character: "汉服", pinyin: "hànfú"),
  Word(
      topic: "Costumes",
      english: "Cheongsam",
      character: "旗袍",
      pinyin: "qípáo"),
  Word(
      topic: "Costumes",
      english: "Tangzhuang",
      character: "唐装",
      pinyin: "tángzhuāng"),
  Word(
      topic: "Costumes",
      english: "Zhongshan Suit",
      character: "中山装",
      pinyin: "zhōngshānzhuāng"),
  Word(
      topic: "Costumes",
      english: "Mao Suit",
      character: "毛装",
      pinyin: "máozhuāng"),
  Word(topic: "Costumes", english: "Qipao", character: "旗袍", pinyin: "qípáo"),
  Word(
      topic: "Costumes",
      english: "Tang Suit",
      character: "唐装",
      pinyin: "tángzhuāng"),
  Word(
      topic: "Costumes",
      english: "Zhongshan Suit",
      character: "中山装",
      pinyin: "zhōngshānzhuāng"),
  Word(topic: "Craft", english: "Craft", character: "工艺", pinyin: "gōngyì"),
  Word(topic: "Craft", english: "Pottery", character: "陶器", pinyin: "táoqì"),
  Word(
      topic: "Craft", english: "Calligraphy", character: "书法", pinyin: "shūfǎ"),
  Word(topic: "Craft", english: "Painting", character: "绘画", pinyin: "huìhuà"),
  Word(topic: "Craft", english: "Sculpture", character: "雕塑", pinyin: "diāosù"),
  Word(topic: "Craft", english: "Embroidery", character: "刺绣", pinyin: "cìxiù"),
  Word(
      topic: "Craft",
      english: "Paper Cutting",
      character: "剪纸",
      pinyin: "jiǎnzhǐ"),
  Word(
      topic: "Craft",
      english: "Kite Making",
      character: "制作风筝",
      pinyin: "zhìzuò fēngzhēng"),
  Word(topic: "Craft", english: "Ceramics", character: "陶瓷", pinyin: "táocí"),
  Word(topic: "Craft", english: "Gold", character: "黄金", pinyin: "huángjīn"),
];
