import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(27.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            width: 2.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: colorScheme.primary,
      ),
      dividerTheme: DividerThemeData(
        thickness: 2,
        space: 2,
        color: appTheme.red90002,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: colorScheme.primary,
          fontSize: 18.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.secondaryContainer,
          fontSize: 15.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.secondaryContainer,
          fontSize: 12.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        displayLarge: TextStyle(
          color: appTheme.blueGray100,
          fontSize: 57.fSize,
          fontFamily: 'Righteous',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: appTheme.gray20001,
          fontSize: 40.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
        ),
        displaySmall: TextStyle(
          color: colorScheme.primary,
          fontSize: 36.fSize,
          fontFamily: 'Paytone One',
          fontWeight: FontWeight.w400,
        ),
        headlineLarge: TextStyle(
          color: appTheme.gray20001,
          fontSize: 32.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
        ),
        headlineMedium: TextStyle(
          color: appTheme.gray400,
          fontSize: 26.fSize,
          fontFamily: 'Oxygen',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.primary,
          fontSize: 25.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        labelLarge: TextStyle(
          color: colorScheme.errorContainer,
          fontSize: 12.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onErrorContainer,
          fontSize: 21.fSize,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        titleMedium: TextStyle(
          color: colorScheme.primary,
          fontSize: 16.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: appTheme.whiteA700A2,
          fontSize: 14.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFFFFFFFF),
    primaryContainer: Color(0XFF4D4D4F),
    secondaryContainer: Color(0X91FFFFFF),

    // Error colors
    errorContainer: Color(0XFFA3A3A3),
    onError: Color(0X99F9FAFF),
    onErrorContainer: Color(0XFF00201C),

    // On colors(text colors)
    onPrimary: Color(0XFF2E2E2E),
    onPrimaryContainer: Color(0XFF0A0A0A),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber40026 => Color(0X26FFBF1A);

  // Black
  Color get black900 => Color(0XFF01050B);
  Color get black90001 => Color(0XFF000000);

  // Blackc
  Color get black9004c => Color(0X4C010E18);

  // Blue
  Color get blue400 => Color(0XFF3993E6);

  // BlueGray
  Color get blueGray100 => Color(0XFFCDE8E1);
  Color get blueGray400 => Color(0XFF778390);
  Color get blueGray800 => Color(0XFF334B47);

  // Cyan
  Color get cyan300 => Color(0XFF54DBC7);

  // DeepOrange
  Color get deepOrangeA700 => Color(0XFFDE2910);

  // Gray
  Color get gray100 => Color(0XFFF0F2F5);
  Color get gray200 => Color(0XFFEFF1EF);
  Color get gray20001 => Color(0XFFEFEFEF);
  Color get gray20002 => Color(0XFFE7E8EB);
  Color get gray300 => Color(0XFFDAE5E1);
  Color get gray30001 => Color(0XFFE5E5E8);
  Color get gray400 => Color(0XFFB3B3B3);
  Color get gray40033 => Color(0X33D0C6AA);
  Color get gray50 => Color(0XFFF7FAF8);
  Color get gray500 => Color(0XFF9E9FA1);
  Color get gray50001 => Color(0XFFA59E8E);
  Color get gray50002 => Color(0XFFACACAD);
  Color get gray50003 => Color(0XFF9098A3);
  Color get gray900 => Color(0XFF252526);
  Color get gray90001 => Color(0XFF200909);
  Color get gray90002 => Color(0XFF560900);
  Color get gray90003 => Color(0XFF470800);
  Color get gray90099 => Color(0X99670D01);

  // GrayCc
  Color get gray100Cc => Color(0XCCF3F2F1);

  // Green
  Color get greenA700 => Color(0XFF1CE230);

  // Lime
  Color get lime900A2 => Color(0XA28D741B);

  // Pink
  Color get pinkA20026 => Color(0X26FF4080);

  // RedD
  Color get red200D1 => Color(0XD1E2A6A6);
  Color get red900D3 => Color(0XD3A20900);

  // Red
  Color get red400 => Color(0XFFE06555);
  Color get red800 => Color(0XFFCF1E25);
  Color get red900 => Color(0XFF7E0E00);
  Color get red90001 => Color(0XFF9A2212);
  Color get red90002 => Color(0XFFA21D1E);
  Color get red90003 => Color(0XFF971200);
  Color get red90099 => Color(0X99881C0E);
  Color get red9009901 => Color(0X998E2011);

  // Redf
  Color get red9007f => Color(0X7F7E0F00);

  // WhiteA
  Color get whiteA700A2 => Color(0XA2FFFEFD);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
